# @format

# See https://pre-commit.com for more information
# See https://pre-commit.ci for more information
ci:
  # Forĝejo/Gitea mirrors will autoclose pull requests. This should decrease
  # the frequency of unnecessary PRs.
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_schedule: quarterly
  skip: [pnpm-install-dev, prettier, latexmk]

default_language_version:
  python: pypy3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md,markdown"]
        # Let's not touch LICENSE files or reuse.software directory
        exclude: ^LICENSES\/.*|LICENSE$
        # File types depending on trailing whitespace. Use identify-cli
        exclude_types: [svg, tsv]

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        # https://github.com/Mikaela/gist/blob/master/doctoc.txt
        args: [--update-only, --notitle]

  - repo: local
    hooks:
      - id: pnpm-install-dev
        name: Install pnpm dev dependencies
        entry: corepack pnpm install -D
        language: system
        always_run: true
        #verbose: true
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: corepack pnpm exec prettier --cache --ignore-unknown --write
        language: system
        # Better handled by pretty-format-json from pre-commit-hooks.
        # Remember to have *.json in .prettierignore!
        exclude_types: [json]
      - id: latexmk
        name: latexmk
        entry: latexmk -quiet
        language: system
        types: [text, tex]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.0.3"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args: [-disable-max-line-length]
